spring:
  liquibase:
    change-log: classpath:liquibase/master.xml
    user: root
    password: root
    enabled: true
    drop-first: false
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

